version: "2"

run:
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go$
      - .*_gen\.go$
      - zz_generated\..*
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/itcamp/ktc
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*_gen\.go$
      - zz_generated\..*
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
