# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ktk_contracts import ai_api_pb2 as ai__api__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiApiStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Explain = channel.unary_unary(
                '/ktk.ai.v1.AiApi/Explain',
                request_serializer=ai__api__pb2.ExplainRequest.SerializeToString,
                response_deserializer=ai__api__pb2.Explanation.FromString,
                _registered_method=True)
        self.PredictPhysics = channel.unary_unary(
                '/ktk.ai.v1.AiApi/PredictPhysics',
                request_serializer=ai__api__pb2.PredictPhysicsRequest.SerializeToString,
                response_deserializer=ai__api__pb2.PhysicsPrediction.FromString,
                _registered_method=True)
        self.PredictBehaviour = channel.unary_unary(
                '/ktk.ai.v1.AiApi/PredictBehaviour',
                request_serializer=ai__api__pb2.PredictBehaviourRequest.SerializeToString,
                response_deserializer=ai__api__pb2.BehaviourRisk.FromString,
                _registered_method=True)
        self.GenerateScenario = channel.unary_unary(
                '/ktk.ai.v1.AiApi/GenerateScenario',
                request_serializer=ai__api__pb2.GenerateScenarioRequest.SerializeToString,
                response_deserializer=ai__api__pb2.ScenarioDraft.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/ktk.ai.v1.AiApi/Analyze',
                request_serializer=ai__api__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=ai__api__pb2.Analysis.FromString,
                _registered_method=True)


class AiApiServicer:
    """Missing associated documentation comment in .proto file."""

    def Explain(self, request, context):
        """FR-AI-02
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictPhysics(self, request, context):
        """FR-AI-03
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBehaviour(self, request, context):
        """FR-AI-04
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateScenario(self, request, context):
        """FR-AI-05 / FR-SCEN-04
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """post-exam разбор
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=ai__api__pb2.ExplainRequest.FromString,
                    response_serializer=ai__api__pb2.Explanation.SerializeToString,
            ),
            'PredictPhysics': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPhysics,
                    request_deserializer=ai__api__pb2.PredictPhysicsRequest.FromString,
                    response_serializer=ai__api__pb2.PhysicsPrediction.SerializeToString,
            ),
            'PredictBehaviour': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBehaviour,
                    request_deserializer=ai__api__pb2.PredictBehaviourRequest.FromString,
                    response_serializer=ai__api__pb2.BehaviourRisk.SerializeToString,
            ),
            'GenerateScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateScenario,
                    request_deserializer=ai__api__pb2.GenerateScenarioRequest.FromString,
                    response_serializer=ai__api__pb2.ScenarioDraft.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=ai__api__pb2.AnalyzeRequest.FromString,
                    response_serializer=ai__api__pb2.Analysis.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ktk.ai.v1.AiApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ktk.ai.v1.AiApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiApi:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.ai.v1.AiApi/Explain',
            ai__api__pb2.ExplainRequest.SerializeToString,
            ai__api__pb2.Explanation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictPhysics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.ai.v1.AiApi/PredictPhysics',
            ai__api__pb2.PredictPhysicsRequest.SerializeToString,
            ai__api__pb2.PhysicsPrediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBehaviour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.ai.v1.AiApi/PredictBehaviour',
            ai__api__pb2.PredictBehaviourRequest.SerializeToString,
            ai__api__pb2.BehaviourRisk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.ai.v1.AiApi/GenerateScenario',
            ai__api__pb2.GenerateScenarioRequest.SerializeToString,
            ai__api__pb2.ScenarioDraft.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.ai.v1.AiApi/Analyze',
            ai__api__pb2.AnalyzeRequest.SerializeToString,
            ai__api__pb2.Analysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
