# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ktk_contracts import model_api_pb2 as model__api__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in model_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimManagerStub:
    """Диспетчер жизненного цикла рабочих подов
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/ktk.sim.v1.SimManager/CreateSession',
                request_serializer=model__api__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=model__api__pb2.SessionEndpoint.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/ktk.sim.v1.SimManager/DestroySession',
                request_serializer=model__api__pb2.SessionId.SerializeToString,
                response_deserializer=model__api__pb2.Ack.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/ktk.sim.v1.SimManager/ListSessions',
                request_serializer=model__api__pb2.Empty.SerializeToString,
                response_deserializer=model__api__pb2.SessionList.FromString,
                _registered_method=True)


class SimManagerServicer:
    """Диспетчер жизненного цикла рабочих подов
    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=model__api__pb2.CreateSessionRequest.FromString,
                    response_serializer=model__api__pb2.SessionEndpoint.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=model__api__pb2.SessionId.FromString,
                    response_serializer=model__api__pb2.Ack.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=model__api__pb2.Empty.FromString,
                    response_serializer=model__api__pb2.SessionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ktk.sim.v1.SimManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ktk.sim.v1.SimManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimManager:
    """Диспетчер жизненного цикла рабочих подов
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.SimManager/CreateSession',
            model__api__pb2.CreateSessionRequest.SerializeToString,
            model__api__pb2.SessionEndpoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.SimManager/DestroySession',
            model__api__pb2.SessionId.SerializeToString,
            model__api__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.SimManager/ListSessions',
            model__api__pb2.Empty.SerializeToString,
            model__api__pb2.SessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelApiStub:
    """Model API — стабильный контракт (FR-SIM-03)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Step = channel.unary_unary(
                '/ktk.sim.v1.ModelApi/Step',
                request_serializer=model__api__pb2.StepRequest.SerializeToString,
                response_deserializer=model__api__pb2.State.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/ktk.sim.v1.ModelApi/GetState',
                request_serializer=model__api__pb2.StateRequest.SerializeToString,
                response_deserializer=model__api__pb2.State.FromString,
                _registered_method=True)
        self.SetState = channel.unary_unary(
                '/ktk.sim.v1.ModelApi/SetState',
                request_serializer=model__api__pb2.State.SerializeToString,
                response_deserializer=model__api__pb2.Ack.FromString,
                _registered_method=True)
        self.InjectFault = channel.unary_unary(
                '/ktk.sim.v1.ModelApi/InjectFault',
                request_serializer=model__api__pb2.InjectFaultRequest.SerializeToString,
                response_deserializer=model__api__pb2.Ack.FromString,
                _registered_method=True)
        self.SetSpeed = channel.unary_unary(
                '/ktk.sim.v1.ModelApi/SetSpeed',
                request_serializer=model__api__pb2.SetSpeedRequest.SerializeToString,
                response_deserializer=model__api__pb2.Ack.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.unary_stream(
                '/ktk.sim.v1.ModelApi/StreamTelemetry',
                request_serializer=model__api__pb2.StreamRequest.SerializeToString,
                response_deserializer=model__api__pb2.Telemetry.FromString,
                _registered_method=True)


class ModelApiServicer:
    """Model API — стабильный контракт (FR-SIM-03)
    """

    def Step(self, request, context):
        """один/несколько шагов интегрирования
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """полное состояние (телеметрия/снапшот)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request, context):
        """установить состояние (init/restore)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectFault(self, request, context):
        """внедрить неисправность (по вызову orchestrator)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeed(self, request, context):
        """коэффициент модельного времени 0.1..10
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request, context):
        """опц. серверный стрим 1 Гц
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=model__api__pb2.StepRequest.FromString,
                    response_serializer=model__api__pb2.State.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=model__api__pb2.StateRequest.FromString,
                    response_serializer=model__api__pb2.State.SerializeToString,
            ),
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=model__api__pb2.State.FromString,
                    response_serializer=model__api__pb2.Ack.SerializeToString,
            ),
            'InjectFault': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectFault,
                    request_deserializer=model__api__pb2.InjectFaultRequest.FromString,
                    response_serializer=model__api__pb2.Ack.SerializeToString,
            ),
            'SetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeed,
                    request_deserializer=model__api__pb2.SetSpeedRequest.FromString,
                    response_serializer=model__api__pb2.Ack.SerializeToString,
            ),
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=model__api__pb2.StreamRequest.FromString,
                    response_serializer=model__api__pb2.Telemetry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ktk.sim.v1.ModelApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ktk.sim.v1.ModelApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelApi:
    """Model API — стабильный контракт (FR-SIM-03)
    """

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.ModelApi/Step',
            model__api__pb2.StepRequest.SerializeToString,
            model__api__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.ModelApi/GetState',
            model__api__pb2.StateRequest.SerializeToString,
            model__api__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.ModelApi/SetState',
            model__api__pb2.State.SerializeToString,
            model__api__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.ModelApi/InjectFault',
            model__api__pb2.InjectFaultRequest.SerializeToString,
            model__api__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ktk.sim.v1.ModelApi/SetSpeed',
            model__api__pb2.SetSpeedRequest.SerializeToString,
            model__api__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ktk.sim.v1.ModelApi/StreamTelemetry',
            model__api__pb2.StreamRequest.SerializeToString,
            model__api__pb2.Telemetry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
