apiVersion: v2
name: auth
description: KTC auth service
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: ktc-service
    version: 0.1.0
    repository: "file://../_service"
