apiVersion: v1
kind: Namespace
metadata:
  name: ktc-app
  labels:
    istio-injection: enabled
    ktc.io/part-of: ktc
---
apiVersion: v1
kind: Namespace
metadata:
  name: ktc-sim
  labels:
    istio-injection: enabled
    ktc.io/part-of: ktc
---
apiVersion: v1
kind: Namespace
metadata:
  name: ktc-ai
  labels:
    istio-injection: enabled
    ktc.io/part-of: ktc
---
apiVersion: v1
kind: Namespace
metadata:
  name: ktc-data
  labels:
    ktc.io/part-of: ktc
---
apiVersion: v1
kind: Namespace
metadata:
  name: ktc-infra
  labels:
    ktc.io/part-of: ktc
---
apiVersion: v1
kind: Namespace
metadata:
  name: ktc-obs
  labels:
    ktc.io/part-of: ktc
