apiVersion: v1
kind: Service
metadata:
  name: {{ include "ktc-service.fullname" . }}
  labels:
    {{- include "ktc-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ktc-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if or .Values.grpcPort .Values.service.grpcPort }}
    - name: grpc
      port: {{ .Values.service.grpcPort | default .Values.grpcPort }}
      targetPort: grpc
    {{- end }}
