{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ktc-service.serviceAccountName" . }}
  labels:
    {{- include "ktc-service.labels" . | nindent 4 }}
---
{{- if .Values.serviceAccount.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ktc-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  {{- toYaml .Values.serviceAccount.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ktc-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ktc-service.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ktc-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
