ktc-service:
  name: ai
  image:
    repository: ""
    tag: latest
  replicaCount: 1
  containerPort: 8080
  grpcPort: 50051
  service:
    port: 80
    grpcPort: 50051
  hpa:
    enabled: false
  nodeSelector:
    ktc.role: ai
  tolerations:
    - key: ai
      value: "true"
      effect: NoSchedule
