replicaCount: 2

image:
  repository: docker.angie.software/angie
  tag: "1.12.1"
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
