apiVersion: v2
name: ktc
description: Umbrella chart for KTC production (app namespace services)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: auth
    version: 0.1.0
    repository: "file://../charts/auth"
  - name: gw
    version: 0.2.0
    repository: "file://../charts/gw"
  - name: constructor
    version: 0.1.0
    repository: "file://../charts/constructor"
  - name: scenario
    version: 0.1.0
    repository: "file://../charts/scenario"
  - name: orchestrator
    version: 0.1.0
    repository: "file://../charts/orchestrator"
  - name: assessment
    version: 0.1.0
    repository: "file://../charts/assessment"
  - name: snapshot
    version: 0.1.0
    repository: "file://../charts/snapshot"
  - name: report
    version: 0.1.0
    repository: "file://../charts/report"
  - name: fe
    version: 0.1.0
    repository: "file://../charts/fe"
